# Generated by Django 3.0.8 on 2020-07-29 04:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 4, 48, 14, 951381, tzinfo=utc)),
        ),
    ]
