# Generated by Django 3.0.8 on 2020-07-29 07:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20200729_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 7, 11, 9, 691028, tzinfo=utc)),
        ),
    ]
